version: '3.8'

services:
  api-gateway:
    container_name: api-gateway
    build:
      context: ./src/api-gateway
    ports:
      - "4000:4000"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

volumes:
  mongo-data:
    driver: local

networks:
  consume-wisely-network:
    driver: bridge
