version: '3.8'

services:
  api-gateway:
    container_name: api-gateway
    build:
      context: ./api-gateway
    ports:
      - "4000:4000"

volumes:
  mongo-data:
    driver: local

networks:
  consume-wisely-network:
    driver: bridge
